### ISSUE TITLE
This doesn't seem to work on safari browsers for me - even windows desktop

### ISSUE THREAD

**Issue by k1n6** [bengarrett/html5Upload#7]
Any experience testing on this windows desktop safari browser?

The request size is constant no matter how many files I choose, the fields appear present in the inspector tool for safari but the files aren't present.

I'm looking into it now.

**Comment by bengarrett** [comment]
It seems this is a known bug in Safari for Windows, but as Apple has abandoned the product ...

> Safari (>= 5.1) on Windows has a bug in multiple file uploads when used together with FormData to do binary uploads; each file will be reported as 0 bytes. Single file selection, however, works fine.

_HTML5 form features_
http://caniuse.com/#search=upload

**Comment by k1n6** [comment]
I also had to make some adjustments for mobile iOS safari as well if you are interested to see those.

**Comment by bengarrett** [comment]
Sure k1n6 I'd be happy to see those.

BTW I created _html5Upload_ more as a JavaScript workaround, as CFML didn't correctly support the HTML5 `<input type="file" multiple>` tag. That has since been fixed in Lucee 4 and 5 so you can implement multiple uploads without the need of JavaScript and not be effected by that Safari issue.

https://luceeserver.atlassian.net/browse/LDEV-793
